// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQm-ipQokHujP5EM_FF0vTHFNpvvt7Jg',
    appId: '1:782138333558:web:6ce98399c884fc77ff4257',
    messagingSenderId: '782138333558',
    projectId: 'pokedex-3412e',
    authDomain: 'pokedex-3412e.firebaseapp.com',
    storageBucket: 'pokedex-3412e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpQ5nvwzLcZD6fl02xU4NT4SIZcZAT9SM',
    appId: '1:782138333558:android:9bad8fa34cf76f6dff4257',
    messagingSenderId: '782138333558',
    projectId: 'pokedex-3412e',
    storageBucket: 'pokedex-3412e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqvDJEHd3toxmMJCPACNB8kF7lVMI9_gw',
    appId: '1:782138333558:ios:d5076e5088f509adff4257',
    messagingSenderId: '782138333558',
    projectId: 'pokedex-3412e',
    storageBucket: 'pokedex-3412e.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqvDJEHd3toxmMJCPACNB8kF7lVMI9_gw',
    appId: '1:782138333558:ios:d5076e5088f509adff4257',
    messagingSenderId: '782138333558',
    projectId: 'pokedex-3412e',
    storageBucket: 'pokedex-3412e.firebasestorage.app',
    iosBundleId: 'com.example.pokedex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfQm-ipQokHujP5EM_FF0vTHFNpvvt7Jg',
    appId: '1:782138333558:web:7ad13874f703c56eff4257',
    messagingSenderId: '782138333558',
    projectId: 'pokedex-3412e',
    authDomain: 'pokedex-3412e.firebaseapp.com',
    storageBucket: 'pokedex-3412e.firebasestorage.app',
  );
}
